apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi  # Specify the storage capacity for the PV
  accessModes:
    - ReadWriteOnce  # Specify the access mode(s) for the PV
  persistentVolumeReclaimPolicy: Retain  # Specify the reclaim policy for the PV
  storageClassName: standard  # Specify the storage class name for the PV
  hostPath:
    path: /path/to/storage  # Specify the host path for the PV

