apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1  # Adjust the number of replicas as per your requirement
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest  # Use the MongoDB Docker image
          ports:
            - containerPort: 27017  # MongoDB default port
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db  # Mount the storage path
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc  # Name of the PVC
