apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-web-deployment
  labels:
    app: counter-web
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: counter-web
  template:
    metadata:
      labels:
        app: counter-web
    spec:
      containers:
        - name: counter-web-container
          image: localhost:32000/container-web-tag:registry  # Replace with your Docker image name and tag
          ports:
            - containerPort: 4000  # Port on which the application is running
          env:
            - name: COUNTER_SERVICE_URL
              value: http://10.152.183.48:4001

#-----------How to run this file, i.e. deployment & expose it
#  Step 1 docker build & push to registry
#  docker build . -t localhost:32000/container-web-tag:registry
#  docker push localhost:32000/container-web-tag:registry

#  kubectl apply -f d1-deployment-web.yaml
#  kubectl expose deployment counter-web-deployment  --type="LoadBalancer"
