Version:
  1: (Jun 3rd, night 3 hours) counter-web deployed in microk8s and accessed via LoadBalancer
#
#------------------------Counter App-----------------------
#

#---------------------------Pipeline-----------------------
State:
  done:
    Dockerise Application:
      1) create dockerfile(s): done for web, service
      2) create docker image: done, working image
      3) created local docker registry: done, and pushed image to local registry
        to use built-in registry.. good one.. https://microk8s.io/docs/registry-built-in
    Kubernetes config to add:
      4) create kube DD for counter-web (frontend) & expose service: done    #Create Kubernetes Deployment YAML files for each component
        (web-deployment.yaml)
        cmd> kubectl expose deployment counter-web-deployment  --type="LoadBalancer"
        now, should see counter-web-deployment in services, use the ClusterIP to access webapp
      5) create pv, pvc, dd for mongodb & expose service: done
        cmd> kubectl expose deployment mongodb-deployment  --type="LoadBalancer"
      6) create kube DD for counter-service (backend) & expose service: #Create a Kubernetes Service YAML file for the backend component to expose it internally within the cluster
  in-progress:
    how to pass clusterip to frontend via dd
  todo:
    7) create kube ingress: #create a Kubernetes Ingress or LoadBalancer Service to expose the frontend component to the outside world
    8) create kube secrets: #to store sensitive info like DB credentials or API keys
    9) create kube config maps: #to manage config files or env variables that need to be injected into the containers
    10) observability:
  issues:
    issue 1 (fixed, i.e. bypassed): | #in web dockerfile
      Step 9/13 : COPY --from=build /app/dist .
      Error response from daemon: COPY failed: stat app/dist: file does not exist
      Failed to deploy '<unknown> Dockerfile: ../counter-app/counter-web/Dockerfile': Can't retrieve image ID from build stream
