apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-web-deployment
  labels:
    app: counter-web
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: counter-web
  template:
    metadata:
      labels:
        app: counter-web
    spec:
      containers:
        - name: counter-web-container
          image: localhost:32000/container-web-tag-3:hello-3  # Replace with your Docker image name and tag
          imagePullPolicy: Always
          ports:
            - containerPort: 4000  # Port on which the application is running
          env:
            - name: COUNTER_SERVICE_URL
              value: "http://10.152.183.48:4001"
