apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Specify the access mode(s) for the PVC (should match the PV)
  resources:
    requests:
      storage: 2Gi  # Specify the desired storage capacity for the PVC (should match the PV)
  storageClassName: standard  # Specify the storage class name for the PVC (should match the PV)
